"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, LockKeyhole, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/logo";
import { Footer } from "@/components/footer";

export default function LoginPage() { return <div className="flex min-h-screen flex-col bg-slate-50 dark:bg-[#0b1322]"><header className="mx-auto flex h-20 w-full max-w-7xl items-center px-5 sm:px-8"><Link href="/"><Logo /></Link></header><main className="mx-auto grid w-full max-w-6xl flex-1 items-center gap-10 px-5 py-12 sm:px-8 lg:grid-cols-2"><div className="hidden lg:block"><p className="eyebrow">Secure clinical workspace</p><h1 className="mt-3 max-w-md text-4xl font-bold tracking-tight text-slate-900 dark:text-white">Welcome back to a more informed workflow.</h1><p className="mt-5 max-w-md text-base leading-7 text-slate-500 dark:text-slate-400">Access your hemoglobinopathy decision support workspace, recent assessments, and model explanations.</p><div className="mt-10 space-y-4">{[[ShieldCheck,"Designed for clinical decision support"],[LockKeyhole,"Role-aware access ready for integration"]].map(([Icon,text]) => { const I = Icon as typeof ShieldCheck; return <div className="flex items-center gap-3 text-sm font-medium text-slate-600 dark:text-slate-300" key={text as string}><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-900/40 dark:text-sky-400"><I size={18} /></span>{text as string}</div>})}</div></div><motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} className="surface mx-auto w-full max-w-md p-6 sm:p-8"><p className="eyebrow">Clinical portal</p><h2 className="mt-2 text-2xl font-bold text-slate-900 dark:text-white">Sign in to HemaInsight</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Use your clinical organization credentials.</p><form className="mt-7 space-y-4" onSubmit={(e) => e.preventDefault()}><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Work email<input type="email" placeholder="name@hospital.org" className="input" /></label><label className="block text-sm font-semibold text-slate-700 dark:text-slate-200">Password<div className="relative"><input type="password" placeholder="••••••••" className="input pr-12" /><LockKeyhole className="absolute right-3.5 top-4 text-slate-400" size={17} /></div></label><div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 text-slate-500"><input type="checkbox" className="accent-brand-600" />Remember this device</label><button type="button" className="font-bold text-brand-600">Forgot password?</button></div><Link href="/dashboard" className="btn-primary mt-2 w-full py-3">Sign in to workspace <ArrowRight size={17} /></Link></form><p className="mt-6 text-center text-xs leading-5 text-slate-400">Prototype environment — no credentials are required.</p></motion.div></main><Footer className="mx-5 sm:mx-8" /></div>; }
